### ISSUE TITLE
Sub-module links on terraform registry are broken.

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/terraform-azurerm-network-security-group#14]
If you go to terraform registry for network security group module and go to one of the sub-modules.  There is a link from there to github that is broken.  The issue is the v in the link.  See below:

link on terraform.io
https://registry.terraform.io/modules/Azure/network-security-group/azurerm/1.0.1/submodules/ActiveDirectory 

Bad
https://github.com/Azure/terraform-azurerm-network-security-group/tree/v1.0.1/modules/ActiveDirectory

Good
https://github.com/Azure/terraform-azurerm-network-security-group/tree/1.0.1/modules/ActiveDirectory

**Comment by yupwei68** [comment]
@rguthriemsft Thanks for opening this issue. And sorry that I need to close it.
