### ISSUE TITLE
Need ability to apply network security group to subnet

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/terraform-azurerm-network-security-group#15]
Not sure why this does not already exist but we have a compartmentalized infrastructure and are trying to deploy an App Service Environment (ASE) using a subnet that was created with a separate deployment.  As part of this...we are creating a new Network Security Group that will get applied to the subnet used by the ASE.  We are easily able to create the NSG as part of our ASE deployment but we are unable to apply it to the subnet as part of the deployment.

**Comment by dcaro** [comment]
@Phydeauxman will look at this after //Build. Thanks for your patience.

**Comment by Marcus-James-Adams** [comment]
Agree, the registry says that this works hand in hand with the virtual-network module but to get it attached to a subnet is a real pain, the option needs adding into one or the other modules to link them especially when you have production systems with multiple subnets you need to keep track of.

**Comment by yupwei68** [comment]
@Phydeauxman Could you provide an example to explain more?
