### ISSUE TITLE
Resource not Populating as Expected

### ISSUE THREAD

**Issue by midacts** [Azure/terraform-azurerm-network-security-group#17]
This is on an imported resource (if that changes anything)
https://paste.ubuntu.com/p/N5pPzCxzRS/

I have the correct information but `terraform plan` says it is going to modify the object.

**Comment by Midacts** [comment]
After looking into this more, it seems that maybe there is something wrong with the [replace code](https://github.com/Azure/terraform-azurerm-network-security-group/blob/master/main.tf#L44):
```
replace( 
		"${lookup(var.custom_rules[count.index], "source_port_range", "*" )}",
		"*",
		"0-65535"
)
```

I haven't been able to find a good way to test/troubleshoot this to get this working  : [[[[

**Comment by Midacts** [comment]
I was able to get this working by replacing this:
```terraform
  source_port_ranges           = "${split(",", replace(  "${lookup(var.custom_rules[count.index], "source_port_range", "*" )}"  ,  "*" , "0-65535" ) )}"
  destination_port_ranges      = "${split(",", replace(  "${lookup(var.custom_rules[count.index], "destination_port_range", "*" )}"  ,  "*" , "0-65535" ) )}"
```

with this:
```terraform
  source_port_range           = "${lookup(var.custom_rules[count.index], "source_port_range", "*" )}"
  destination_port_range      = "${lookup(var.custom_rules[count.index], "destination_port_range", "*" )}"
```

It looks like someone added in the split and replace because they needed it for something?
But it looks like they replace * with 0-65535 (for some reason).


### Question
Is this an acceptable change?

**Comment by yupwei68** [comment]
@midacts ,on fact your code https://paste.ubuntu.com/p/N5pPzCxzRS/ works perfectly without error now. It's a problem the `source_port_range` support "*",but `source_port_ranges` doesn't. And here we uses `source_port_ranges` to support a list of port ranges. Please ref: https://www.terraform.io/docs/providers/azurerm/r/network_security_rule.html
