### ISSUE TITLE
Use * as default source_port_ranges

### ISSUE THREAD

**Issue by irnc** [Azure/terraform-azurerm-network-security-group#21]
Azure Portal warns agains `0-65535` value, telling _The recommended value for source port ranges is * (Any). Port filtering is mainly used with destination port._

Could this module use recommended * (Any)? What is the reason to specify whole range instead?

**Comment by DamaniN** [comment]
Seeing the same issue.

**Comment by perithompson** [comment]
same issue here

**Comment by yupwei68** [comment]
@irnc Thanks for opening this issue. On fact, `source_port_range` support "*" for any, but `source_port_ranges` doesn't support.Please refer:https://www.terraform.io/docs/providers/azurerm/r/network_security_rule.html
