### ISSUE TITLE
Usage of 'split' function within the 'source_port_ranges' resource parameter

### ISSUE THREAD

**Issue by tcreatorxxx** [Azure/terraform-azurerm-network-security-group#25]
Hi, there.

When reading official docs for **azurerm_network_security_rule** resource, I see:

> source_port_ranges - (Optional) **List** of source ports or port ranges

So, does it mean I need to wrap it in brackets to indicate that the output is actually a list?

Currently you have:
`source_port_ranges = "${split(",", replace("${lookup(var.predefined_rules[count.index], "source_port_range", "*" )}" ,  "*", "0-65535" ))}"`, which is actually just a string, not a list.

Or, Terraform is doing automatic string-to-list conversion for **split** function result?

**Comment by Midacts** [comment]
I gave up caring about this module after it's been 6+ morning that with no
reply.

**Comment by fepere** [comment]
Hello, any news about this issue ? the source_port_rage and destination_port_range should be on the list of parameters to use/setup, due few rules we use that, can you fix it ?

**Comment by yupwei68** [comment]
@tcreatorxxx Thanks for opening this issue. You could assign a list of source_port_ranges as:
`source_port_range      = "1024,1025,1026"`
And split function does it.
