### ISSUE TITLE
Removing  module causes resource group to be deleted.

### ISSUE THREAD

**Issue by DamaniN** [Azure/terraform-azurerm-network-security-group#26]
We have a Terraform script that creates a resource group using `azurerm_resource_group`. We then used this `terraform-azurerm-network-security-group` module to create our network security groups. As an input parameter, we provided the resource group that we had created earlier in the TF. 

Later on, we removed the NSG as it was not needed anymore. It wasn't obvious from `terraform plan` that the update would also remove the entire resource group and its contents. Running `terraform apply` did, in fact, delete the resource group and its contents from Azure. 

After looking at this module more in-depth, it appears that the module itself is creating a resource group. In our case since we have everything in the same resource group and supplied that resource group to the module, removing the NSG wiped out the resource group that had our entire configuration. Interestingly, the module didn't complain that the RG already existed when creating the NSG. 

Removing this module from a TF script should not cause the entire RG to be deleted, especially if there are other resources still using it (either managed by TF or not). This module should not be creating or manipulating RGs. Instead, that should be handled outside of the module. 

I did find a workaround to this. That is to use `terraform state rm` to remove all of the entries created by this module. Then use `terraform import` to import the remaining entries back into the TF configuration. Now when the module is removed it will not delete the RG. It may be cleaner to just find the RG entry created by the module and `terraform state rm` that but I didn't have a chance to test it.

**Comment by yupwei68** [comment]
1.With Terrafrom v.0.12, it shows error for duplicated creation of resource group while applying.
2.The following could work: 
    a)`terraform plan `
    b)`terraform import module.myModuleName.azurerm_resource_group.nsg /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroupName` (import resource group state)
  c)`terraform apply`
  d)`terraform destroy -target=module.myModuleName.azurerm_network_security_group.nsg`

I hope it could help.

**Comment by boldandbusted** [comment]
So, this is a terrible bug. Deleting one instance of the module will destroy ANY OTHER RESOURCES in that same Resource Group. I tried to use this module to demonstrate Terraform, and was scratching my head to figure out why deleting one instance of the module was deleting EVERYTHING ELSE... This should be a priority to fix, as the chance for outages is strong...

**Comment by yupwei68** [comment]
HI @DamaniN ,Thanks for opening this issue. We have fixed it in the latest release v3.0.0
