### ISSUE TITLE
Feature request: Add ability to enable/disable

### ISSUE THREAD

**Issue by philwinder** [Azure/terraform-azurerm-network-security-group#30]
Terraform doesn't allow you to enable/disable modules in the usual pattern, using a count.

Would it be possible to add an enable/disable flag that is passed through to the count of all resources, to prevent this module being created?

Typical use cases include when you are applying the same code to different environments. Sometimes you want to only enable a specific NSG for a specific environment.

Thanks.

**Comment by yupwei68** [comment]
@philwinder could you provide an example
