### ISSUE TITLE
Feature request: Do not create resource group

### ISSUE THREAD

**Issue by philwinder** [Azure/terraform-azurerm-network-security-group#31]
99% of the time, I already have the resource group. If not, I can create it easily. This module should create the NSG, not the RG, I believe the RG is out of scope.

Would it be possible to either:
1) Remove the resource group creation
2) Add the ability to pass in the previously created resource group name?

And also note, this dangerous behaviour that has just caught me out. If you pass in the name of a rg that already exists, it works. But then if you delete your NSG, it completely deletes the old RG too! Ouch.

Thanks

**Comment by Marcus-James-Adams** [comment]
That seems to be common behaviour on a lot of modules, I end up having to download them to my own repo and remove the offending lines,  but that then beats the point of having a registry :-(

**Comment by yupwei68** [comment]
@philwinder Thanks for opening this issue. Please refer to the similar issue here:https://github.com/Azure/terraform-azurerm-network-security-group/issues/26
