### ISSUE TITLE
terraform 0.12.0

### ISSUE THREAD

**Issue by stefan-rapp** [Azure/terraform-azurerm-network-security-group#32]
Seems like the module does not work correctly with the new version terraform 0.12.0, because of the map for the nsg rules.

Error: Invalid value for input variable

  on terraform.tfvars line 104:
 104: vm_dc_subnet_nsg_predfined  =     [
 105:                                         {
 106:                                             name                   = "SSH"
 107:                                             priority               = "500"
 108:                                             source_address_prefix  = ["10.0.3.0/24"]
 109:                                         },
 110:                                         {
 111:                                             name                   = "LDAP"
 112:                                             source_port_range      = "1024-1026"
 113:                                         }
 114:                                     ]

The given value is not valid for variable "vm_dc_subnet_nsg_predfined": all
list elements must have the same type.

Any recommendations?

**Comment by paddyhitch** [comment]
I think it has something to do with how terraform 0.12 handles lists vs 0.11

https://github.com/hashicorp/terraform/issues/21281

**Comment by yupwei68** [comment]
hi @stefan-rapp, Thanks for opening this issue. This problem has been solved and released in [v2.0.0](https://github.com/Azure/terraform-azurerm-network-security-group/releases/tag/2.0.0)
