### ISSUE TITLE
Attaching NSG to specified vnets?

### ISSUE THREAD

**Issue by assareh** [Azure/terraform-azurerm-network-security-group#33]
The documentation states "This Terraform module deploys a Network Security Group (NSG) in Azure and optionally attach it to the specified vnets."

I do not see a way to specify a vnet. This functionality doesn't seem to be implemented in the module.

**Comment by yupwei68** [comment]
The module has predefined rules for azurerm_network_security_group. Please take a look at the examples in package: https://github.com/Azure/terraform-azurerm-network-security-group/tree/master/modules
