### ISSUE TITLE
Add ICMP as supported protocol for security_rule

### ISSUE THREAD

**Issue by wadejd** [Azure/terraform-azurerm-network-security-group#34]
Now NSG security rules support ICMP as a supported protocol in the rule. The resource module needs to be updated to support this: https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#security-rules  (see Protocol)

Currently, the resource module produced the following error: 
Error: expected security_rule.14.protocol to be one of [* Tcp Udp], got ICMP

**Comment by danielfears** [comment]
This isn't to do with the module, but the AzureRM provider, and looks to be in the next release.
