### ISSUE TITLE
Error: A resource with the ID ... already exists (AzureRM Provider v2)

### ISSUE THREAD

**Issue by tecris** [Azure/terraform-azurerm-network-security-group#47]
Dear Team,

First, thank you for your work, I am a happy user of your module ;)

With v2.0 of the AzureRM Provider (plus terraform v0.21.23 & Azure/network-security-group/azurerm v2.0.0) I am getting this error:
`Error: A resource with the ID ... already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for `azurerm_resource_group` for more information.

`I attached a basic example that can be used to reproduce this error.
Am I doing something wrong, or the module needs to be updated for v2.0.0 of the AzureRM Provider?
[test.tar.gz](https://github.com/Azure/terraform-azurerm-network-security-group/files/4303688/test.tar.gz)

cheers
eugen

**Comment by yupwei68** [comment]
HI @tecris ,Thanks for opening this issue. We have fixed it in the latest release v3.0.0
