### ISSUE TITLE
Feature Request:  customize location

### ISSUE THREAD

**Issue by larryclaman** [Azure/terraform-azurerm-network-security-group#49]
Request:  Allow resource location to be customized.

This module sets the nsg location to the same location as the resource group.  However, there are many valid cases where the vnet/subnet location is not the same as the resource group.  As currently implemented, I don't see a way to override this.

**Comment by larryclaman** [comment]
Created PR #51 to support this feature request

**Comment by yupwei68** [comment]
Thanks for your contribution!
