### ISSUE TITLE
Example given for list[] of "destination_address_prefix" values in variables.tf - does not appear to be supported by main.tf

### ISSUE THREAD

**Issue by jturver1** [Azure/terraform-azurerm-network-security-group#50]
This example is given in variables.tf for input:

```
variable "destination_address_prefix" {
  type    = list(string)
  default = ["*"]
  <mark># Example ["10.0.3.0/32","10.0.3.128/32"] or ["VirtualNetwork"] </mark>
}
```

However, unlike the transformation of "*" to "0-65535" for e.g. source_port_ranges, there is no equivalent translation for destination_port_prefixes. 

Are *lists* of ranges of prefixes intended to be handled for source and destinations, or is it a limitation?

Many thanks,
Justin

**Comment by yupwei68** [comment]
Hi @jturver1 ,thanks for opening this issue. On fact, we use `source_port_ranges`, `destination_port_range`, `source_address_prefix` and `destination_address_prefix` in this module, mainly serving our predefined rules. As `source_port_ranges` doesn't take `*` as a valid character, we does an transformation. There examples in variables.tf may have been out of date , I'll fix it in the next release. 
```
variable "destination_address_prefix" {
  type    = string
  default = "*"
  <mark># Example "10.0.3.0/32" or "VirtualNetwork" </mark>
}
```
