### ISSUE TITLE
Support for application security groups as destination/source parameter

### ISSUE THREAD

**Issue by ghost** [Azure/terraform-azurerm-network-security-group#53]
the _azurerm_network_security_rule_ resource supports application security groups as destination and source instead auf subnet prefixes by the parameter `source_application_security_group_ids` and `destination_application_security_group_ids`.

It would be nice if this module supports this official.

https://www.terraform.io/docs/providers/azurerm/r/network_security_rule.html

**Comment by vishalmaheswari** [comment]
Realy appreciate if you have support for source_application_security_group_ids and destination_application_security_group_ids
