### ISSUE TITLE
No example of optionally associating to subnet

### ISSUE THREAD

**Issue by Lucero7919** [Azure/terraform-azurerm-network-security-group#54]
There are no listed variables or options to associating the NSG to an existing subnet - Please provide in documentation.

**Comment by yupwei68** [comment]
Hi @Lucero7919 , thanks for opening this issue. There are examples in module vnet showing how to associating nsg to subnet. Please refer https://github.com/Azure/terraform-azurerm-vnet#example-adding-a-network-security-rule-for-ssh.
Sorry that I have to close this issue temporarily. Please reopen it when anything unclear.
