### ISSUE TITLE
source_address_prefix is not set using custom rules

### ISSUE THREAD

**Issue by carlosdoliveira** [Azure/terraform-azurerm-network-security-group#63]
---
name: 'Bug Report:'
about: Create a report to help us improve
title: 'source_address_prefix is not set using custom rules'
labels: 'issue'
assignees: ''

---

**Version**
Module version: 3.3.1
Azurerm Provider version: 2.37
Terraform version: 0.13

**Terraform code**
``` hcl
module "NSG" {
  source              = "Azure/network-security-group/azurerm"
  security_group_name = "NSG"
  resource_group_name = azurerm_resource_group.resourcegroup.name
  location            = azurerm_resource_group.resourcegroup.location
  tags                = var.tags
  custom_rules = [
    {
      name                    = "rule1"
      priority                = 100
      direction               = "Inbound"
      source_address_prefixes = ["20x.xxx.xxx.82", "20x.xxx.xxx.210", "18x.xxx.xxx.90", "20x.xxx.xxx.194"]
      destination_port_range  = "22058"
    },
    {
      name                   = "rule2"
      priority               = 160
      direction              = "Inbound"
      access                 = "Allow"
      destination_port_range = "443"
    }
  ]
  depends_on = [azurerm_resource_group.resourcegroup]
}
```

**Reproduce Steps**
1. Terraform apply

**Expected behavior**
The security rule should have all inserted source_address_prefixes.

**Actual behavior**
It actually is not chaging anything, and it sets source_address_prefix to "Any".
![image](https://user-images.githubusercontent.com/23587299/100381884-c6490080-2ff8-11eb-8ce8-75ac7163fda0.png)

**Comment by yupwei68** [comment]
Hi @carlosdoliveira , thanks for opening this issue. Sorry that I can't reproduce this bug. You hcl configuration works fine for me.
![image](https://user-images.githubusercontent.com/56525716/100401379-47a1a100-3094-11eb-803c-95519d5b7470.png)
Please run "terraform plan" and see if the following changes  are shown:
![image](https://user-images.githubusercontent.com/56525716/100401471-88011f00-3094-11eb-85cb-fab26cc8fa25.png)

**Comment by carlosdoliveira** [comment]
@yupwei68, just found out that I had to reinitialize this module to version 3.4.1. I didn't realize the new version at terraform registry. Thanks for the efforts. Issue closed.
