### ISSUE TITLE
source_port_range does not support "Any" - leads to warning in Azure

### ISSUE THREAD

**Issue by vamsee-konda** [Azure/terraform-azurerm-network-security-group#70]
In a custom rule setting the source_port_range to * leads to Terraform creating rule with 0-65535 as the source port range. 
```json
{
            name = "SuspiciousIPs_DenyAll"
            priority               = 101
            direction              = "Inbound"
            access                 = "Deny"
            protocol               = "*"
            source_port_range      = "*"
            destination_port_range = "*"
            source_address_prefix  = "xxx.xxx.xxx.xxx/xx"
            destination_address_prefix = "VirtualNetwork"
            description            = "SuspiciousIPs_DenyAll"
}
```
![image](https://user-images.githubusercontent.com/17186076/117348005-52483980-ae6f-11eb-8db4-9fefa2fb5114.png)

But Azure doesn't like this - there is a warning displayed which reads "The recommended value for source port ranges is * (Any). Port filtering is mainly used with destination port.". The use of "Any" is not supported in source_port_range or destination_port_range.

Can this be fixed please?

**Comment by PopaRadu** [comment]
I have same problem. A solution for this would help.

**Comment by yupwei68** [comment]
close for https://github.com/Azure/terraform-azurerm-network-security-group/pull/69
