### ISSUE TITLE
Case incorrect on Protocol field

### ISSUE THREAD

**Issue by dsmithcloud** [Azure/terraform-azurerm-network-security-group#76]
Getting the following errors when attempting to use the ActiveDirectory predefined rules:

expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got UDP

Changing the values in rules.tf from TCP to Tcp after init and then running plan results in success.

terraform block in use shown below:
terraform {
  required_version = ">=1.2.9"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0.0"
    }
  }
}

**Comment by koralowiec** [comment]
Hi, I also got this error - I created a PR #77 which should fix this issue.

Steps to reproduce:

`terraform.tf`:

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.28.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

`main.tf`:

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "test-rg"
  location = "West Europe"
}

module "nsg" {
  source  = "Azure/network-security-group/azurerm"
  version = "3.6.0"

  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  security_group_name   = "nsg"
  source_address_prefix = ["0.0.0.0/0"]
  predefined_rules = [
    {
      name     = "SSH"
      priority = "500"
    }
  ]
}
```

```bash
terraform init
terraform plan
```

Running `plan` results in the error:

```
│ Error: expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
│ 
│   with module.nsg.azurerm_network_security_rule.predefined_rules[0],
│   on .terraform/modules/nsg/main.tf line 22, in resource "azurerm_network_security_rule" "predefined_rules":
│   22:   protocol                                   = element(var.rules[lookup(var.predefined_rules[count.index], "name")], 2)
│ 
```

When `source` changed to a local module with changes from #77 like here:

```hcl
module "nsg" {
  # source  = "Azure/network-security-group/azurerm"
  # version = "3.6.0"
  source = "/home/arek/horsing-around/terraform/terraform-azurerm-network-security-group"
```

I can run `terraform plan` without the error (`terraform init` is needed after the change above).
